# Generated by Django 3.2.13 on 2022-07-30 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200000000),
            preserve_default=False,
        ),
    ]
